IzvorniKod/Wild8/Wild8/Models/Cart/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Owin.Security;

namespace Wild8.Models.Cart
{
    public class Cart
    {
        private List<CartItem> items;

        public decimal TotalPrice
        {
            get
            {
                decimal sum = 0;
                foreach (var cartItem in items)
                {
                    sum += cartItem.Price;
                }
                return sum;
            }
        }

        public Cart()
        {
            items = new List<CartItem>();
        }

        public void AddItem(CartItem Item)
        {
            items.Add(Item);
        }

        public IReadOnlyList<CartItem> Items
        {
            get
            {
                return items.AsReadOnly();
            }
        }

        public void RemoveItem(CartItem Item)
        {
            items.Remove(Item);
        }

        public decimal ChangeItemCount(CartItem item, int newCount)
        {
            CartItem cartItem =items.Find(i => i.Equals(item));
            if (cartItem != null)
            {
                cartItem.Count = newCount;
            }
            else
            {
                return 0;
            }
            return cartItem.Price;
        }

        public int Count()
        {
            return items.Count;
        }

        public void Clear()
        {
            items.Clear();
        }

        public bool IsEmpty()
        {
            return items.Count == 0;
        }
    }
}

IzvorniKod/Wild8/Wild8/Models/Cart/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Wild8.StaticInfo;

namespace Wild8.Models.Cart
{
    public class CartModelView
    {
        public string StartTime { get; }
        public string EndTime { get; }
        public Cart Cart { get; }

        public CartModelView(Cart cart)
        {
            Cart = cart;
            RestaurauntInfo info = RestaurauntInfo.Instance;
            
            StartTime = info.RestStartH + ":" + info.RestStartM;
            EndTime = info.RestEndH + ":" + info.RestEndM;
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/AdminController.cs
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNet.SignalR;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Hubs;
using Wild8.Hubs.Util;
using Wild8.Models;
using Wild8.Models.ModelViews;
using Wild8.StaticInfo;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class AdminController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();
        private CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings["StorageConnectionString"]);

        private bool LoggedOut()
        {
            if (SessionExtension.GetUser(Session) == null)
            {
                return true;
            }
            return false;
        }

        // GET: Admin
        public ActionResult Index()
        {
            var user = SessionExtension.GetUser(Session);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        ////////////////////////////////////
        //  Orders
        ////////////////////////////////////
        [HttpGet]
        public ActionResult Orders()
        {
            return PartialView("Orders/Orders");
        }

        [HttpPost]
        public ActionResult Order(string JsonOrder)
        {
            var order = JsonConvert.DeserializeObject<Order>(JsonOrder);
            order.OrderDate = DateTime.Now;
            JsonOrder = JsonConvert.SerializeObject(order);

            OrdersSet.GetInstance().Add(JsonOrder); //Send order to workers
            var context = GlobalHost.ConnectionManager.GetHubContext<OrderHub>();
            context.Clients.Group(OrderHub.WORKERS).addNewOrder(JsonOrder);

            SessionExtension.GetCart(Session).Clear();  //Clear cart
            return PartialView("~/Views/Cart/ThankYouMsg.cshtml");
        }

        ////////////////////////////////////
        //  Meal add, edit, delete
        ////////////////////////////////////
        [HttpPost]
        public ActionResult AcceptOrder(string orderJSON, string employeeId, string message)
        {
            if (LoggedOut()) return HttpNotFound();
            var acceptedOrder = JsonConvert.DeserializeObject<Order>(orderJSON);
            acceptedOrder.EmpolyeeID = employeeId;
            acceptedOrder.AcceptanceDate = DateTime.Now;

            OrderInfo info = new OrderInfo()
            {
                Info = RestaurauntInfo.Instance,
                Message = message,
                Order = acceptedOrder
            };

            updateMealOrderCount(acceptedOrder);

            using (StringWriter sw = new StringWriter())
            {
                ControllerContext.Controller.ViewData.Model = info;
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, "Receipt");
                ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                var receipt = sw.ToString();

                MailUtil.Instance.SendReceiptTo(acceptedOrder.Email, "Potvrda narudžbe", receipt);
            }

            db.Orders.Add(acceptedOrder);
            db.SaveChanges();
            return Content("Narudzba potvrdjena");
        }

        private void updateMealOrderCount(Order acceptedOrder)
        {
            //I know this is affull but do not know better method
            foreach (var orderDetail in acceptedOrder.OrderDetails)
            {
                var meal = db.Meals.FirstOrDefault(m => m.Name == orderDetail.MealName);
                if (meal != null) meal.NumberOfOrders += orderDetail.Count;
            }
            db.SaveChanges();
        }

        [HttpPost]
        public ActionResult RefuseOrder(string email, string message)
        {
            if (LoggedOut()) return HttpNotFound();
            MailUtil.Instance.SendReceiptTo(email, "Naruđba odbijena", message);
            return Content("Narudzba odbijena");
        }

        [HttpGet]
        public ActionResult AddEditDelMenu()
        {
            if (LoggedOut()) return HttpNotFound();
            return PartialView("AddEditDelMealsPartial");
        }

        [HttpGet]
        public ActionResult AddMeal()
        {
            if (LoggedOut()) return HttpNotFound();
            AddEditMealModelView newMeal = new AddEditMealModelView()
            {
                Categories = db.Categories.ToList(),
                AddOns = db.AddOns.ToList()
            };
            return PartialView("AddMeal", newMeal);
        }

        [HttpPost]
        public ActionResult AddMeal([Bind(Include = "MealID,Name,Description,CategoryID,IsAvailable")] Meal meal, IEnumerable<string> SelectedAddOns, HttpPostedFileBase upload, string[] MealType, string[] Price)
        {
            if (LoggedOut()) return HttpNotFound();
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    meal.ImagePath = UploadPhoto(upload);
                }
                meal = db.Meals.Add(meal);

                if (SelectedAddOns != null)
                {
                    foreach (var item in SelectedAddOns)
                    {
                        db.MealAddOns.Add(new MealAddOn()
                        {
                            AddOnID = item,
                            MealID = meal.MealID
                        });
                    }
                }

                if (MealType != null && Price != null)
                {
                    for (int i = 0; i < MealType.Length; i++)
                    {
                        string mealTypeName = MealType[i];
                        string priceString = Price[i];
                        if (mealTypeName != null && mealTypeName.Length > 0 && priceString != null && priceString.Length > 0)
                        {
                            db.MealTypes.Add(new MealType()
                            {
                                MealID = meal.MealID,
                                MealTypeName = MealType[i],
                                Price = decimal.Parse(Price[i], CultureInfo.InvariantCulture)
                            });
                        }
                    }
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception)
                    {
                        return Content("Jelo " + meal.Name + " već postoji.", MediaTypeNames.Text.Plain);
                    }
                }
                return Content("Jelo " + meal.Name + " je spremljeno.", MediaTypeNames.Text.Plain);
            }
            else
            {
                return Content("Neočekivana greška.", MediaTypeNames.Text.Plain);
            }
        }

        private string UploadPhoto(HttpPostedFileBase photo)
        {
            string fileName = Guid.NewGuid().ToString() + Path.GetFileName(photo.FileName);
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("meals");
            container.CreateIfNotExists();
            container.SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileName);
            blockBlob.UploadFromStream(photo.InputStream);
            return blockBlob.StorageUri.PrimaryUri.AbsoluteUri;
        }

        private void DeletePhoto(string path)
        {
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("meals");
            container.CreateIfNotExists();
            container.SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            try
            {
                CloudBlockBlob blockBlob = new CloudBlockBlob(new Uri(path), storageAccount.Credentials);
                blockBlob.DeleteIfExists();
            }
            catch (Exception)
            {
            }
        }

        [HttpGet]
        public ActionResult EditMeal(int? id)
        {
            if (LoggedOut()) return HttpNotFound();
            if (id == null)
            {   //Load list of meals in database and render it to user
                return PartialView("EditMealList", db.Meals.ToList());
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            List<string> addOns = new List<string>();
            foreach (var item in meal.AddOns)
            {
                addOns.Add(item.AddOn.AddOnID);
            }

            var mealTypes = db.MealTypes.Where(r => r.MealID == meal.MealID);

            AddEditMealModelView newMeal = new AddEditMealModelView()
            {
                Categories = db.Categories.ToList(),
                AddOns = db.AddOns.ToList(),
                Meal = meal,
                SelectedCategory = meal.CategoryID,
                SelectedAddOns = addOns,
                MealTypes = mealTypes
            };

            return PartialView("EditMeal", newMeal);
        }

        [HttpPost]

IzvorniKod/Wild8/Wild8/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class CartController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        // GET: Cart
        public ActionResult Index()
        {
            return View(new CartModelView(SessionExtension.GetCart(Session)));
        }

        [HttpPost]
        public int RemoveMeal(int MealID, string Type, int Count, string[] AddOns)
        {
            CartItem item = createCartItem(MealID, Type, Count, AddOns);
            Cart cart = SessionExtension.GetCart(Session);
            cart.RemoveItem(item);
            int count = cart.Count();
            Session["CartCount"] = count;
            return count;
        }

        public decimal ChangeCartItemSize(int MealID, string Type, int oldCount, string[] AddOns, int newCount)
        {
            CartItem item = createCartItem(MealID, Type, oldCount, AddOns);
            Cart cart = SessionExtension.GetCart(Session);
            return cart.ChangeItemCount(item, newCount);
        }

        private CartItem createCartItem(int MealID, string Type, int Count, string[] AddOns)
        {
            Cart cart = SessionExtension.GetCart(Session);
            MealType MealType = db.MealTypes.Find(MealID, Type);
            CartItem CartItem = new CartItem(MealType, Count);

            if (AddOns != null)
            {
                foreach (var item in AddOns)
                {
                    AddOn addOn = db.AddOns.Find(item);
                    CartItem.AddMealAddOn(addOn);
                }
            }
            return CartItem;
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/MealsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Models.ModelViews;

namespace Wild8.Controllers
{
    public class MealsController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();
        // GET: Meals

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            if (!meal.IsAvailable)
            {
                return HttpNotFound();
            }
            meal.Comments = meal.Comments.OrderByDescending(item => item.CommentDate).ToList();
            MealWithPrice mwp = new MealWithPrice()
            {
                Meal = meal,
                Types = db.MealTypes.Where(type => type.MealID == meal.MealID).ToList(),
                IsHot = false
            };

            return View(mwp);
        }

        // POST: Meals/AddNewComment
        // TODO shity stars
        [HttpPost]
        public ActionResult AddNewComment(int? ID, string Username, string Message, int? Rating)
        {
            if (ModelState.IsValid)
            {
                Comment newComment = new Comment
                {
                    CommentDate = DateTime.Now,
                    Message = Message,
                    Username = Username,
                    Grade = Rating == null ? 5 : (int)Rating,
                    MealID = ID
                };
                db.Comments.Add(newComment);
                db.SaveChanges();

                return PartialView("~/Views/Meals/Comment.cshtml", newComment);
            }

            return null;
        }

        //POST
        public int AddToCart(int count, int mealID, string mealTypeName, string[] addOnNames)
        {
            MealType type = db.MealTypes.Find(mealID, mealTypeName);
            CartItem item = new CartItem(type, count);

            if (addOnNames != null)
            {
                foreach (var addOnName in addOnNames)
                {
                    item.AddMealAddOn(db.AddOns.Find(addOnName));
                }
            }

            Cart cart = SessionExtension.GetCart(Session);
            cart.AddItem(item);
            SessionExtension.SetCartItemCount(cart.Count(), Session);
            return cart.Count();
        }
    }
}

IzvorniKod/Wild8/Wild8/Views/Cart/CartItemsList.cshtml
@using Antlr.Runtime.Tree
@model IReadOnlyList<CartItem>

@foreach (var item in Model)
{
    <tr data-meal-id="@item.MealType.Meal.MealID"
        data-meal-name="@item.MealType.Meal.Name"
        data-type="@item.MealType.MealTypeName"
        data-count="@item.Count"
        data-url="@Url.Action("RemoveMeal", "Cart")"
        data-base-price ="@(item.Price)"
        data-change-count-url="@Url.Action("ChangeCartItemSize","Cart")">
        <!--Todo put image of a meal here-->
        <td class="img-col">
            <a href="@Url.Action("Details", "Meals", new { id = item.MealType.MealID })"><img class="food-image img-responsive" style="max-width:128px; max-height:128px;" src="@item.MealType.Meal.ImagePath"></a>
        </td>
        <td class="name-col">
            @item.MealType.Meal.Name
        </td>
        <td class="size-col">
            @item.MealType.MealTypeName
        </td>
        <td class="size-col">
            <select class="1-10">@for (int i = 1; i <= 10; i++)
            {
                if (i == item.Count)
                {
                    <option selected="selected">@i</option>                
                }
                else
                {
                    <option>@i</option>
                }
            }</select>
        </td>
        <td class="addon-col">
            <ul>
                @foreach (var addon in item.AddOns)
                {
                    <li class="addon">@addon.AddOnID</li>
                }
            </ul>
        </td>
        <td class="price-col" align="right">
            <p class="price">@item.Price HRK</p>
        </td>
        <td class="remove-col">
            <button type="button" class="btn btn-danger pull-right removeFromCartBtn">Ukloni</button>
            <label class="pull-right"></label>
        </td>       
    </tr>
}

IzvorniKod/Wild8/Wild8/Views/Cart/Index.cshtml
@using Wild8.StaticInfo
@model CartModelView

@{
    ViewBag.Title = "Wild8 | Košarica";
}

@section Scripts {
    <script type="text/javascript" src="~/Scripts/ViewScripts/Cart_View.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.0.min.js"></script>
    <script src="@Url.Content("~/signalr/hubs   ")"></script>
    <script>
        jQuery.extend(jQuery.validator.messages, {
            required: "Ovo polje je obavezno",
            remote: "Please fix this field.",
            email: "Neispravna email adresa",
            url: "Please enter a valid URL.",
            date: "Please enter a valid date.",
            dateISO: "Please enter a valid date (ISO).",
            number: "Please enter a valid number.",
            digits: "Please enter only digits.",
            creditcard: "Please enter a valid credit card number.",
            equalTo: "Please enter the same value again.",
            accept: "Please enter a value with a valid extension.",
            maxlength: jQuery.validator.format("Please enter no more than {0} characters."),
            minlength: jQuery.validator.format("Please enter at least {0} characters."),
            rangelength: jQuery.validator.format("Please enter a value between {0} and {1} characters long."),
            range: jQuery.validator.format("Please enter a value between {0} and {1}."),
            max: jQuery.validator.format("Please enter a value less than or equal to {0}."),
            min: jQuery.validator.format("Please enter a value greater than or equal to {0}.")
        });

    </script>
}
@section Styles{
    <link rel="stylesheet" type="text/css" href="~/Content/cart.css" />
}

<div id="dvCategoryResults" class="container">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Košarica</h3>
            </div>
            <div class="panel-body">
                <table class="table table-condensed" style="border-collapse: collapse;">
                    <thead id="head-underline">
                        <tr>
                            <th>Slika jela</th>
                            <th>Naziv jela</th>
                            <th>Veličina</th>
                            <th>Količina</th>
                            <th>Dodaci</th>
                            <th class="pull-right">Cijena</th>
                        </tr>
                    </thead>

                    <tbody class="displayed" id="orders-list">
                        @{
                            Html.RenderPartial("CartItemsList", Model.Cart.Items);
                        }
                    </tbody>
                </table>
                <div class="panel-body">
                    <table class="table table-condensed" style="border-collapse: collapse;">
                        <thead id="head-underline">
                            <tr>
                                <th>Ukupno</th>
                            </tr>
                        </thead>
                        <tbody class="displayed">
                            <tr>
                                <td id="total-price">@Model.Cart.TotalPrice HRK</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <form class="form-horizontal" id="order-form"
                      data-start-time="@Model.StartTime"
                      data-end-time="@Model.EndTime"
                      data-min-order="@RestaurauntInfo.Instance.MinimalOrderPrice">
                    <fieldset>
                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Name">Ime i prezime</label>
                            <div class="col-md-4">
                                <input id="client-name" name="Name" class="form-control input-md" required="" type="text">
                                <span class="help-block">Ime i prezime</span>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Address">Adresa</label>
                            <div class="col-md-4">
                                <input id="client-address" name="Address" class="form-control input-md" required="" type="text">
                                <span class="help-block">Ulica, grad i poštanski broj (odvojeni zarezom)</span>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Phone">Telefon</label>
                            <div class="col-md-4">
                                <input id="client-phone" name="Phone" class="form-control input-md" required="" type="text">
                                <span class="help-block">Broj telefona</span>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Email">Email</label>
                            <div class="col-md-4">
                                <input id="client_email" name="client_email" class="form-control input-md" required="" type="text">
                                <span class="help-block">Adresa e-pošte</span>
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Note">Napomena</label>
                            <div class="col-md-4">
                                <textarea class="form-control" id="client-note" name="Note"></textarea>
                            </div>
                        </div>

                        <!-- Button -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="Accept"></label>
                            <div class="trebamiime">
                                <button name="accept" id="make-order-btn" class="btn btn-success" data-url="@Url.Action("Order","Admin")">Potvrdi narudžbu</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <div id="cart-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
</div>

IzvorniKod/Wild8/Wild8/Views/Cart/ThankYouMsg.cshtml
<div class="container jumbotron" style="border-radius: 20px">
    <div style="text-align: center">
        <h1>
            Hvala na narudžbi
        </h1>
        <p>
            Vaša narudžba se obrađuje.
            <br>
            Potvrda o narudžbi će biti poslana na danu e-mail adresu.
        </p>
    </div>
</div>