IzvorniKod/Wild8/Wild8/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class CartController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        // GET: Cart
        public ActionResult Index()
        {
            return View(new CartModelView(SessionExtension.GetCart(Session)));
        }

        [HttpPost]
        public int RemoveMeal(int MealID, string Type, int Count, string[] AddOns)
        {
            CartItem item = createCartItem(MealID, Type, Count, AddOns);
            Cart cart = SessionExtension.GetCart(Session);
            cart.RemoveItem(item);
            int count = cart.Count();
            Session["CartCount"] = count;
            return count;
        }

        public decimal ChangeCartItemSize(int MealID, string Type, int oldCount, string[] AddOns, int newCount)
        {
            CartItem item = createCartItem(MealID, Type, oldCount, AddOns);
            Cart cart = SessionExtension.GetCart(Session);
            return cart.ChangeItemCount(item, newCount);
        }

        private CartItem createCartItem(int MealID, string Type, int Count, string[] AddOns)
        {
            Cart cart = SessionExtension.GetCart(Session);
            MealType MealType = db.MealTypes.Find(MealID, Type);
            CartItem CartItem = new CartItem(MealType, Count);

            if (AddOns != null)
            {
                foreach (var item in AddOns)
                {
                    AddOn addOn = db.AddOns.Find(item);
                    CartItem.AddMealAddOn(addOn);
                }
            }
            return CartItem;
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.StaticInfo;

namespace Wild8.Controllers
{
    public class CommentsController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Where(c => c.Meal == null).OrderByDescending(item => item.CommentDate);
            return View(comments.ToList());
        }


        [HttpPost]
        public ActionResult AddNewComment(string Username, string Message, int Rating)
        {
            if (ModelState.IsValid)
            {
                //Update restourant grade
                RestaurauntInfo info = RestaurauntInfo.Instance;
                var commentNumber = db.Comments.Count();
                var newRestourantGrade = (decimal)((commentNumber * info.RestourantGrade + Rating) / (commentNumber + 1));
                info.RestourantGrade = Math.Round(newRestourantGrade, 2);

                //Save comment
                Comment newComment = new Comment
                {
                    CommentDate = DateTime.Now,
                    Message = Message,
                    Username = Username,
                    Grade = Rating,
                };
                db.Comments.Add(newComment);
                db.SaveChanges();

                return PartialView("~/Views/Meals/Comment.cshtml", newComment);
            }
            return null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class LoginController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        // GET: Login
        public ActionResult Index()
        {
            var user = SessionExtension.GetUser(Session);
            if (user != null)
            {
                return RedirectToAction("Index", "Admin");
            }

            return View();
        }

        [HttpPost]
        public bool Login(string username, string password)
        {
            username = TextUtils.sanitize(username);
            password = TextUtils.sanitize(password);

            Employee employee = db.Employees.Find(username.Trim());
            if (employee == null)
            {
                return false;
            }

            if (!employee.isEmployed)
            {
                return false;
            }

            if (TextUtils.SHA256Hash(password) != employee.Password)
            {
                return false;
            }

            SessionExtension.SetUser(Session, employee);

            return true;
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/MenuController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Models.ModelViews;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class MenuController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        public readonly static string BY_NAME = "Ime (A-Ž)";
        public readonly static string BY_NAME_REVERSE = "Ime (Ž-A)";
        public readonly static string BY_PRICE = "Cijena (najniže prvo)";
        public readonly static string BY_PRICE_REVERSE = "Cijena (najviše prvo)";
        public readonly static string BY_GRADE = "Ocjena (najviše prvo)";
        public readonly static string BY_POPULARITY = "Popularnost (više naručivane)";

        // GET: Menu
        public ActionResult Index()
        {
            List<MealWithPrice> mealWPrice = new List<MealWithPrice>();

            //If already selected category load that category again
            Category activeCategory = (Category)(Session["Category"]);
            List<Category> catgories = db.Categories.ToList();
            if (activeCategory == null)
            {
                activeCategory = catgories.First();
            }
            List<MealWithPrice> meals = loadMeals(activeCategory);
            sortMeals(meals, BY_NAME);

            MenuModelView modelView = new MenuModelView()
            {
                activeCategory = catgories.First(),
                Meals = meals,
                Categories = catgories
            };

            return View(modelView);
        }

        [HttpPost]
        public ActionResult ChangeCategory(int categoryId, string sort)
        {
            List<MealWithPrice> meals = loadMeals(db.Categories.Find(categoryId));
            sortMeals(meals, sort);
            return PartialView("MealsList", meals);
        }

        [HttpPost]
        public int AddToCart(int mealID, int count, string mealTypeName, string[] addOnNames)
        {
            MealType type = db.MealTypes.Find(mealID, mealTypeName);
            CartItem item = new CartItem(type, count);

            if (addOnNames != null)
            {
                foreach (var addOnName in addOnNames)
                {
                    item.AddMealAddOn(db.AddOns.Find(addOnName));
                }
            }

            Cart cart = SessionExtension.GetCart(Session);
            cart.AddItem(item);
            SessionExtension.SetCartItemCount(cart.Count(), Session);
            return cart.Count();
        }

        private List<MealWithPrice> loadMeals(Category category)
        {
            List<MealWithPrice> mealWPrice = new List<MealWithPrice>();
            double average = category.Meals.Average(m => m.NumberOfOrders);
            foreach (Meal m in category.Meals)
            {
                if (!m.IsAvailable) continue;

                MealWithPrice mwp = new MealWithPrice()
                {
                    Meal = m,
                    Types = db.MealTypes.Where(type => type.MealID == m.MealID).ToList(),
                    IsHot = average != 0.0 && m.NumberOfOrders > average
                };
                mealWPrice.Add(mwp);
            }

            return mealWPrice;
        }

        private static void sortMeals(List<MealWithPrice> meals, string sort)
        {
            if (sort == BY_NAME)
            {
                meals.Sort((m1, m2) => m1.Meal.Name.CompareTo(m2.Meal.Name));
            }
            else if (sort == BY_NAME_REVERSE)
            {
                meals.Sort((m1, m2) => -m1.Meal.Name.CompareTo(m2.Meal.Name));
            }
            else if (sort == BY_PRICE)
            {
                meals.Sort((m1, m2) => Decimal.Compare(m1.Types.Min().Price, m2.Types.Min().Price));
            }
            else if (sort == BY_PRICE_REVERSE)
            {
                meals.Sort((m1, m2) => -Decimal.Compare(m1.Types.Min().Price, m2.Types.Min().Price));
            }
            else if (sort == BY_GRADE)
            {
                meals.Sort((m1, m2) => m1.Meal.Grade - m2.Meal.Grade);
            }
            else if (sort == BY_POPULARITY)
            {
                meals.Sort((m1, m2) => m1.Meal.NumberOfOrders.CompareTo(m2.Meal.NumberOfOrders));
            }
        }
    }
}

IzvorniKod/Wild8/Wild8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="~/images/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/SharedLayout.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    @RenderSection("Scripts", false)
    @RenderSection("Styles", false)
</head>
<body>
    <div id="header-wrap">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="header">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wildNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">Wild8</a>
                </div>
                <div class="collapse navbar-collapse" id="wildNavbar">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span> Početna</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Menu")"><span class="glyphicon glyphicon-cutlery"></span> Jelovnik</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Comments")"><span class="glyphicon glyphicon-comment"></span> Komentari</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Contacts")"><span class="glyphicon glyphicon-globe"></span> Kontakt</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a id="cartCount" href="@Url.Action("Index", "Cart")"><span class="glyphicon glyphicon-shopping-cart"></span> @SessionExtension.GetCart(Session).Count()</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery.bootstrap-autohidingnavbar.min.js"></script>

    <script>
        $("div.navbar-fixed-top").autoHidingNavbar();
    </script>
    @RenderBody()
    <footer>
        <hr class="featurette-divider">
        <p class="pull-right">
            <a href="#top">Idi na vrh</a>
        </p>
        <p>
            © Wild8 ugostiteljski obrt. · <a href="@Url.Action("Index", "Login")">Prijava osoblja</a>
        </p>
    </footer>
</body>
</html>