IzvorniKod/Wild8/Wild8/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wild8.StaticInfo;

namespace Wild8.Controllers
{
    public class ContactsController : Controller
    {
        public ActionResult Index()
        {
            return View(RestaurauntInfo.Instance);
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.ModelViews;
using Wild8.StaticInfo;

namespace Wild8.Controllers
{
    public class HomeController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();


        public ActionResult Index()
        {
            List<Meal> meals = db.Meals.OrderByDescending(meal => meal.NumberOfOrders).ToList();
            HomePageModelView modelView = new HomePageModelView()
            {
                FirstMeal = meals[0],
                SecondMeal = meals[1],
                ThirdMeal = meals[2]
            };
            
            //Don't ask why is this here
            RestaurauntInfo instance = RestaurauntInfo.Instance;
            if (instance.RestourantGrade == -1)
            {
                instance.RestourantGrade = Math.Round(Convert.ToDecimal(db.Comments.Average(c => c.Grade)), 2);
                instance.SaveData();
            }

            return View(modelView);
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/MealsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Models.ModelViews;

namespace Wild8.Controllers
{
    public class MealsController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();
        // GET: Meals

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            if (!meal.IsAvailable)
            {
                return HttpNotFound();
            }
            meal.Comments = meal.Comments.OrderByDescending(item => item.CommentDate).ToList();
            MealWithPrice mwp = new MealWithPrice()
            {
                Meal = meal,
                Types = db.MealTypes.Where(type => type.MealID == meal.MealID).ToList(),
                IsHot = false
            };

            return View(mwp);
        }

        // POST: Meals/AddNewComment
        // TODO shity stars
        [HttpPost]
        public ActionResult AddNewComment(int? ID, string Username, string Message, int? Rating)
        {
            if (ModelState.IsValid)
            {
                Comment newComment = new Comment
                {
                    CommentDate = DateTime.Now,
                    Message = Message,
                    Username = Username,
                    Grade = Rating == null ? 5 : (int)Rating,
                    MealID = ID
                };
                db.Comments.Add(newComment);
                db.SaveChanges();

                return PartialView("~/Views/Meals/Comment.cshtml", newComment);
            }

            return null;
        }

        //POST
        public int AddToCart(int count, int mealID, string mealTypeName, string[] addOnNames)
        {
            MealType type = db.MealTypes.Find(mealID, mealTypeName);
            CartItem item = new CartItem(type, count);

            if (addOnNames != null)
            {
                foreach (var addOnName in addOnNames)
                {
                    item.AddMealAddOn(db.AddOns.Find(addOnName));
                }
            }

            Cart cart = SessionExtension.GetCart(Session);
            cart.AddItem(item);
            SessionExtension.SetCartItemCount(cart.Count(), Session);
            return cart.Count();
        }
    }
}

IzvorniKod/Wild8/Wild8/Controllers/MenuController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wild8.DAL;
using Wild8.Models;
using Wild8.Models.Cart;
using Wild8.Models.ModelViews;
using Wild8.Utils;

namespace Wild8.Controllers
{
    public class MenuController : Controller
    {
        private RestaurauntContext db = new RestaurauntContext();

        public readonly static string BY_NAME = "Ime (A-Ž)";
        public readonly static string BY_NAME_REVERSE = "Ime (Ž-A)";
        public readonly static string BY_PRICE = "Cijena (najniže prvo)";
        public readonly static string BY_PRICE_REVERSE = "Cijena (najviše prvo)";
        public readonly static string BY_GRADE = "Ocjena (najviše prvo)";
        public readonly static string BY_POPULARITY = "Popularnost (više naručivane)";

        // GET: Menu
        public ActionResult Index()
        {
            List<MealWithPrice> mealWPrice = new List<MealWithPrice>();

            //If already selected category load that category again
            Category activeCategory = (Category)(Session["Category"]);
            List<Category> catgories = db.Categories.ToList();
            if (activeCategory == null)
            {
                activeCategory = catgories.First();
            }
            List<MealWithPrice> meals = loadMeals(activeCategory);
            sortMeals(meals, BY_NAME);

            MenuModelView modelView = new MenuModelView()
            {
                activeCategory = catgories.First(),
                Meals = meals,
                Categories = catgories
            };

            return View(modelView);
        }

        [HttpPost]
        public ActionResult ChangeCategory(int categoryId, string sort)
        {
            List<MealWithPrice> meals = loadMeals(db.Categories.Find(categoryId));
            sortMeals(meals, sort);
            return PartialView("MealsList", meals);
        }

        [HttpPost]
        public int AddToCart(int mealID, int count, string mealTypeName, string[] addOnNames)
        {
            MealType type = db.MealTypes.Find(mealID, mealTypeName);
            CartItem item = new CartItem(type, count);

            if (addOnNames != null)
            {
                foreach (var addOnName in addOnNames)
                {
                    item.AddMealAddOn(db.AddOns.Find(addOnName));
                }
            }

            Cart cart = SessionExtension.GetCart(Session);
            cart.AddItem(item);
            SessionExtension.SetCartItemCount(cart.Count(), Session);
            return cart.Count();
        }

        private List<MealWithPrice> loadMeals(Category category)
        {
            List<MealWithPrice> mealWPrice = new List<MealWithPrice>();
            double average = category.Meals.Average(m => m.NumberOfOrders);
            foreach (Meal m in category.Meals)
            {
                if (!m.IsAvailable) continue;

                MealWithPrice mwp = new MealWithPrice()
                {
                    Meal = m,
                    Types = db.MealTypes.Where(type => type.MealID == m.MealID).ToList(),
                    IsHot = average != 0.0 && m.NumberOfOrders > average
                };
                mealWPrice.Add(mwp);
            }

            return mealWPrice;
        }

        private static void sortMeals(List<MealWithPrice> meals, string sort)
        {
            if (sort == BY_NAME)
            {
                meals.Sort((m1, m2) => m1.Meal.Name.CompareTo(m2.Meal.Name));
            }
            else if (sort == BY_NAME_REVERSE)
            {
                meals.Sort((m1, m2) => -m1.Meal.Name.CompareTo(m2.Meal.Name));
            }
            else if (sort == BY_PRICE)
            {
                meals.Sort((m1, m2) => Decimal.Compare(m1.Types.Min().Price, m2.Types.Min().Price));
            }
            else if (sort == BY_PRICE_REVERSE)
            {
                meals.Sort((m1, m2) => -Decimal.Compare(m1.Types.Min().Price, m2.Types.Min().Price));
            }
            else if (sort == BY_GRADE)
            {
                meals.Sort((m1, m2) => m1.Meal.Grade - m2.Meal.Grade);
            }
            else if (sort == BY_POPULARITY)
            {
                meals.Sort((m1, m2) => m1.Meal.NumberOfOrders.CompareTo(m2.Meal.NumberOfOrders));
            }
        }
    }
}

IzvorniKod/Wild8/Wild8/Views/Home/Index.cshtml
@using Wild8.StaticInfo
@model Wild8.Models.ModelViews.HomePageModelView

@{
    ViewBag.Title = "Wild8";
}

@section Scripts
{
    <script type="text/javascript" src="~/Scripts/menu_view.js"></script>
    <script type="text/javascript">
            $(document).ready(function()
            {
                $('.carousel').carousel(
                {
                    interval: 3250
                });

                $('.carousel').carousel('cycle');
            });
    </script>
}
@section Styles
{
    <link rel="stylesheet" type="text/css" href="~/Content/homepage.css" />
}
<!-- Carousel  -->
<div id="wildCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#wildCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#wildCarousel" data-slide-to="1"></li>
        <li data-target="#wildCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/images/carousel_images/Wild8_interior.jpg" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Wild8</h1>
                    <p>Najbolja jela s roštilja.</p>
                    <p>
                        <a class="btn btn-large btn-primary" href="#restaurant_info">Više informacija</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/carousel_images/Wild8_sample_food.jpg" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Širok izbor</h1>
                    <p>Preko 100 različitih delikatesa.</p>
                    <p>
                        <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Menu")">Jelovnik</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/images/carousel_images/Wild8_delivery.jpg" class="img-responsive">
            <div class="container">
                <div class="carousel-caption">
                    <h1 style="color: black" class="header_special">Besplatna dostava</h1>
                    <p class="paragraph-special">Dostava pred vaša kućna vrata.</p>
                    <p>
                        <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Contacts")">Posjetite nas</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#wildCarousel" data-slide="prev"><span class="icon-prev"></span></a>
    <a class="right carousel-control" href="#wildCarousel" data-slide="next"><span class="icon-next"></span></a>
</div>


<!-- Marketing messaging and featurettes -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-md-4 text-center">
            <img class="img-circle" src="@Model.FirstMeal.ImagePath" alt="Nemas srece">
            <h2>@Model.FirstMeal.Name</h2>
            <p>
                <a class="btn btn-default" href="@Url.Action("Details", "Meals", new { id = Model.FirstMeal.MealID })">Više »</a>
            </p>
        </div>
        <div class="col-md-4 text-center">
            <img class="img-circle" src="@Model.SecondMeal.ImagePath" alt="Nemas srece">
            <h2>@Model.SecondMeal.Name</h2>
            <p>
                <a class="btn btn-default" href="@Url.Action("Details", "Meals", new { id = Model.SecondMeal.MealID })">Više »</a>
            </p>
        </div>
        <div class="col-md-4 text-center">
            <img class="img-circle" src="@Model.ThirdMeal.ImagePath" alt="Nemas srece">
            <h2>@Model.ThirdMeal.Name</h2>
            <p>
                <a class="btn btn-default" href="@Url.Action("Details", "Meals", new { id = Model.ThirdMeal.MealID })">Više »</a>
            </p>
        </div>
    </div>
    <!-- /.row -->
    <!-- FEATURETTES -->
    <a name="restaurant_info"></a>
    <!-- anchor link for carousel button -->
    <hr class="featurette-divider">
    <div class="featurette">
        <img class="featurette-image img-circle pull-right img-responsive" src="~/images/featurette_restaurant.jpg">
        <h2 class="featurette-heading">Restoran <span class="text-muted">Wild8</span></h2>
        <p class="lead">Prosječna ocjena restorana: @RestaurauntInfo.Instance.RestourantGrade</p>
        <p class="lead">
            @RestaurauntInfo.Instance.RestauranutHomepageInfo
        </p>
    </div>
    <hr class="featurette-divider">
    <div class="featurette">
        <img class="featurette-image img-circle pull-left img-responsive" src="~/images/owner.jpeg">
        <h2 class="featurette-heading">Vlasnik <span class="text-muted">@RestaurauntInfo.Instance.OwnerName</span></h2>
        <p class="lead">@RestaurauntInfo.Instance.OwnerHomepageInfo</p>
    </div>
    <!-- /FEATURETTES -->
    <!-- FOOTER -->
</div>